const noEmptyStr = { type: "string", minLength: 1 };

export default {
  type: "object",
  additionalProperties: false,
  properties: {
    entry: noEmptyStr,
    file: { type: "string" },
    type: { type: "string", pattern: "^(cjs|esm|umd)$" },
    disableTypeCheck: { type: "boolean" },
    target: noEmptyStr,
    runtimeHelpers: { type: "boolean" },
    browserFiles: { type: "array" },
    nodeVersion: { type: "number" },
    nodeFiles: { type: "array" },
    lazy: { type: "boolean" },
    extraBabelPresets: { type: "array" },
    extraBabelPlugins: { type: "array" },
    cssModules: { oneOf: [{ type: "boolean" }, { type: "object" }] },
    extractCSS: { type: "boolean" },
    injectCSS: { oneOf: [{ type: "boolean" }, { instanceof: "Function" }] },
    extraPostCSSPlugins: { type: "array" },
    extraRollupPlugins: { type: "array" },
    autoprefixer: { type: "object" },
    include: { oneOf: [{ type: "string" }, { type: "object" }, { type: "array" }] },
    replace: { type: "object" },
    inject: { type: "object" },
    extraExternals: { type: "array" },
    externalsExclude: { type: "array" },
    typescriptOpts: { type: "object" },
    nodeResolveOpts: { type: "object" },
    minify: { type: "boolean" },
    umd: {
      type: "object",
      additionalProperties: false,
      properties: {
        globals: { type: "object" },
        name: noEmptyStr,
        sourcemap: { oneOf: [{ type: "boolean" }, { type: "string", pattern: "^(inline|hidden)$" }] },
      },
    },
  },
};
